const Router = require('express')
const router = new Router()
const userController = require ('../controller/user.controller')

router.post('/user', userController.createUser)
router.get('/user', userController.getUsers)
router.get('/user/:id', userController.getOneUser)
router.put('/user', userController.updateUser)
router.put('/user/:id/role', userController.updateUserRole)
router.delete('/user/:id', userController.deleteUser)
router.post('/token', userController.setToken)
router.put('/token', userController.refreshToken)
router.delete('/token', userController.deleteToken)
router.get('/profile', userController.getProfile)
router.put('/profile', userController.updateProfile)
router.post('/sendOneTimePassword', userController.sendOneTimePassword)
router.get('/user/:id/payments', userController.getUserPayments)
router.get('/user/:id/purchases', userController.getUserPurchases)

module.exports = router